<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Phing Batchtest" tests="35" assertions="95" failures="3" errors="6" time="0.025189">
    <testsuite name="BaseFortissimoCommandTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/BaseFortissimoCommandTest.php" tests="2" assertions="13" failures="0" errors="0" time="0.002145">
      <testcase name="testExpects" class="BaseFortissimoCommandTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/BaseFortissimoCommandTest.php" line="12" assertions="12" time="0.000726"/>
      <testcase name="testDoRequest" class="BaseFortissimoCommandTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/BaseFortissimoCommandTest.php" line="51" assertions="1" time="0.001419"/>
    </testsuite>
    <testsuite name="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" tests="8" assertions="13" failures="3" errors="0" time="0.003789">
      <testcase name="testGetConfiguration" class="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" line="11" assertions="1" time="0.000361"/>
      <testcase name="testIncludePath" class="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" line="16" assertions="1" time="0.000523">
        <failure type="PHPUnit_Framework_ExpectationFailedException">ConfigTest::testIncludePath
Failed asserting that &lt;integer:3&gt; matches expected &lt;integer:1&gt;.

/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php:19
/usr/lib/php/phing.php:37
</failure>
      </testcase>
      <testcase name="testRequest" class="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" line="26" assertions="1" time="0.000705">
        <failure type="PHPUnit_Framework_ExpectationFailedException">ConfigTest::testRequest
Failed asserting that &lt;integer:12&gt; matches expected &lt;integer:1&gt;.

/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php:37
/usr/lib/php/phing.php:37
</failure>
      </testcase>
      <testcase name="testGroup" class="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" line="45" assertions="1" time="0.000585">
        <failure type="PHPUnit_Framework_ExpectationFailedException">ConfigTest::testGroup
Failed asserting that &lt;integer:3&gt; matches expected &lt;integer:1&gt;.

/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php:56
/usr/lib/php/phing.php:37
</failure>
      </testcase>
      <testcase name="testGroupInRequest" class="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" line="64" assertions="3" time="0.000465"/>
      <testcase name="testDatasources" class="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" line="80" assertions="4" time="0.000418"/>
      <testcase name="testLoggers" class="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" line="104" assertions="1" time="0.000367"/>
      <testcase name="testCaches" class="ConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/ConfigTest.php" line="109" assertions="1" time="0.000365"/>
    </testsuite>
    <testsuite name="FortissimoConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoConfigTest.php" tests="5" assertions="27" failures="0" errors="0" time="0.004784">
      <testcase name="testConstructor" class="FortissimoConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoConfigTest.php" line="13" assertions="1" time="0.001088"/>
      <testcase name="testGetConfig" class="FortissimoConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoConfigTest.php" line="20" assertions="2" time="0.001003"/>
      <testcase name="testIsLegalRequestName" class="FortissimoConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoConfigTest.php" line="27" assertions="21" time="0.000491"/>
      <testcase name="testHasRequest" class="FortissimoConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoConfigTest.php" line="40" assertions="1" time="0.001153"/>
      <testcase name="testGetRequest" class="FortissimoConfigTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoConfigTest.php" line="47" assertions="2" time="0.001049"/>
    </testsuite>
    <testsuite name="FortissimoContextDumpTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoContextDumpTest.php" tests="1" assertions="0" failures="0" errors="1" time="0.000908">
      <testcase name="testDoCommand" class="FortissimoContextDumpTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoContextDumpTest.php" line="16" assertions="0" time="0.000908">
        <error type="PHPUnit_Framework_Error_Warning">FortissimoContextDumpTest::testDoCommand
include(&lt;?xml version="1.0"?&gt;
&lt;commands xmlns="http://technosophos.com/2009/1.1/commands.xml"&gt;
&lt;request name="testDoCommand"&gt;
  &lt;cmd name="mock" invoke="MockCommand"/&gt;
  &lt;cmd name="testDoCommand1" invoke="FortissimoContextDump"/&gt;
&lt;/request&gt;
&lt;/commands&gt;
): failed to open stream: No such file or directory

/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1530
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1530
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:273
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php:231
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoContextDumpTest.php:17
/usr/lib/php/phing.php:37
</error>
      </testcase>
    </testsuite>
    <testsuite name="FortissimoEchoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoEchoTest.php" tests="1" assertions="0" failures="0" errors="1" time="0.000793">
      <testcase name="testDoCommand" class="FortissimoEchoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoEchoTest.php" line="17" assertions="0" time="0.000793">
        <error type="PHPUnit_Framework_Error_Warning">FortissimoEchoTest::testDoCommand
include(&lt;?xml version="1.0"?&gt;
&lt;commands xmlns="http://technosophos.com/2009/1.1/commands.xml"&gt;
&lt;request name="testDoCommand"&gt;
  &lt;cmd name="echo" invoke="FortissimoEcho"&gt;
    &lt;param name="text"&gt;Echo&lt;/param&gt;
  &lt;/cmd&gt;
&lt;/request&gt;
&lt;/commands&gt;
): failed to open stream: No such file or directory

/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1530
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1530
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:273
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php:231
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoEchoTest.php:18
/usr/lib/php/phing.php:37
</error>
      </testcase>
    </testsuite>
    <testsuite name="FortissimoExceptionsTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExceptionsTest.php" tests="2" assertions="0" failures="0" errors="2" time="0.001786">
      <testcase name="testException" class="FortissimoExceptionsTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExceptionsTest.php" line="20" assertions="0" time="0.000940">
        <error type="PHPUnit_Framework_Error_Warning">FortissimoExceptionsTest::testException
include(&lt;?xml version="1.0"?&gt;
  &lt;commands&gt;
  &lt;request name="foo"&gt;
    &lt;cmd name="test" invoke="ExceptionThrowingCommand"/&gt;
  &lt;/request&gt;
  &lt;request name="div"&gt;
    &lt;cmd name="test" invoke="ErrorThrowingCommand"/&gt;
  &lt;/request&gt;
  &lt;logger name="fail" invoke="FortissimoArrayInjectionLogger"/&gt;
  &lt;/commands&gt;): failed to open stream: No such file or directory

/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1530
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1530
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:273
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php:231
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExceptionsTest.php:21
/usr/lib/php/phing.php:37
</error>
      </testcase>
      <testcase name="testErrorToException" class="FortissimoExceptionsTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExceptionsTest.php" line="29" assertions="0" time="0.000846">
        <error type="PHPUnit_Framework_Error_Warning">FortissimoExceptionsTest::testErrorToException
include(&lt;?xml version="1.0"?&gt;
  &lt;commands&gt;
  &lt;request name="foo"&gt;
    &lt;cmd name="test" invoke="ExceptionThrowingCommand"/&gt;
  &lt;/request&gt;
  &lt;request name="div"&gt;
    &lt;cmd name="test" invoke="ErrorThrowingCommand"/&gt;
  &lt;/request&gt;
  &lt;logger name="fail" invoke="FortissimoArrayInjectionLogger"/&gt;
  &lt;/commands&gt;): failed to open stream: No such file or directory

/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1530
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1530
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:273
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php:231
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExceptionsTest.php:30
/usr/lib/php/phing.php:37
</error>
      </testcase>
    </testsuite>
    <testsuite name="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" tests="9" assertions="25" failures="0" errors="0" time="0.003705">
      <testcase name="testConstructor" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="11" assertions="2" time="0.000387"/>
      <testcase name="testSize" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="19" assertions="2" time="0.000423"/>
      <testcase name="testHas" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="29" assertions="2" time="0.000445"/>
      <testcase name="testGet" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="35" assertions="2" time="0.000413"/>
      <testcase name="testAdd" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="42" assertions="2" time="0.000417"/>
      <testcase name="testRemove" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="51" assertions="2" time="0.000405"/>
      <testcase name="testToArray" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="58" assertions="1" time="0.000365"/>
      <testcase name="testFromArray" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="64" assertions="3" time="0.000432"/>
      <testcase name="testIterator" class="FortissimoExecutionContextTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoExecutionContextTest.php" line="73" assertions="9" time="0.000418"/>
    </testsuite>
    <testsuite name="FortissimoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php" tests="7" assertions="17" failures="0" errors="2" time="0.007279">
      <testcase name="testConstructor" class="FortissimoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php" line="13" assertions="1" time="0.001303"/>
      <testcase name="testFetchParams" class="FortissimoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php" line="19" assertions="9" time="0.001228"/>
      <testcase name="testHandleRequest" class="FortissimoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php" line="57" assertions="3" time="0.001296"/>
      <testcase name="testLogger" class="FortissimoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php" line="73" assertions="3" time="0.001161"/>
      <testcase name="testRequestCache" class="FortissimoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php" line="82" assertions="0" time="0.000800">
        <error type="QueryPathParseException">FortissimoTest::testRequestCache
QueryPathParseException: DOMDocument::load(): ParsePI: PI php never end ... in /Users/mbutcher/Code/Fortissimo/test/test_commands.php, line: 116 (/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/core/QueryPath/QueryPath.php: 17)

/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/core/QueryPath/QueryPath.php:17
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/core/QueryPath/QueryPath.php:17
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/core/QueryPath/QueryPath.php:2
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php:85
/usr/lib/php/phing.php:37
</error>
      </testcase>
      <testcase name="testForwardRequest" class="FortissimoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php" line="124" assertions="0" time="0.001108">
        <error type="FortissimoRequestNotFoundException">FortissimoTest::testForwardRequest
FortissimoRequestNotFoundException: Request testForwardRequest1 not found

/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:1711
/Users/mbutcher/Code/Fortissimo/Fortissimo/skel/src/Fortissimo.php:371
/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php:126
/usr/lib/php/phing.php:37
</error>
      </testcase>
      <testcase name="testAutoloader" class="FortissimoTest" file="/Users/mbutcher/Code/Fortissimo/test/Tests/Fortissimo/FortissimoTest.php" line="134" assertions="1" time="0.000383"/>
    </testsuite>
  </testsuite>
</testsuites>
